### ISSUE TITLE
Issue when executing LPB command

### ISSUE THREAD

**Issue by NovaPixell** [MrIvanPlays/IvanCord#4]
Here a screen.
![2021-01-09_08 38 27](https://user-images.githubusercontent.com/55632135/104086221-1d77fd00-5256-11eb-9dc0-24448a109be6.png)

**Comment by NovaPixell** [comment]
A way to fix this?

**Comment by MrIvanPlays** [comment]
hey sorry for not being able to respond for like 3 months :D 
can u try with build #62 please?
