### ISSUE TITLE
Support in FlameCord

### ISSUE THREAD

**Issue by andreasdc** [MrIvanPlays/IvanCord#8]
Hey, do you agree for your patches to be implemented in FlameCord? I think some of them are nice.
Here's the issue: https://github.com/2lstudios-mc/FlameCord/issues/90

**Comment by MrIvanPlays** [comment]
as long as you provide credit yes.

**Comment by xism4** [comment]
> 

The patches that you actually ask for, are from FlameCord so i don't see why asking for credits.

**Comment by MrIvanPlays** [comment]
2 patches here are from flamecord. nothing else

**Comment by xIsm4** [comment]
> 2 patches here are from flamecord. nothing else

Yeah, and he wants to add those xd.

**Comment by andreasdc** [comment]
This guy is brainless, don't listen to him.

**Comment by xIsm4** [comment]
> This guy is brainless, don't listen to him.

True, i am the guy that asks for apply the same patches to other fork.

**Comment by andreasdc** [comment]
> > This guy is brainless, don't listen to him.
> 
> True, i am the guy that asks for apply the same patches to other fork.

I'm not going to argue with you, you can't even understand simple words, so who knows what will you get from a little bit more complicated statements. Good luck in your life and don't spam issues with useless comments.

**Comment by xIsm4** [comment]
> I'm not going to argue with you, you can't even understand simple words, so who knows what will you get from a little bit more complicated statements. Good luck in your life and don't spam issues with useless comments.

Actually, didn't spam?
And no, are not useless due you want to put the same patches of FlameCord?
Any ways look the lastest patch, he doesn't need anymore limits or close on exceptions.
Due on handlerboss firewall's any exception (Avoiding Readtimeout)

**Comment by MrIvanPlays** [comment]
Im not going to tolerate any violence.
