### ISSUE TITLE
Skin API

### ISSUE THREAD

**Issue by felipepasc** [MrIvanPlays/IvanCord#9]
Opa gostei muito do seu projeito!
Queria muito te pedir para adicionar uma forma de register um SkinProvider 
para eu conseguir utilizar a api de skin!

**Comment by MrIvanPlays** [comment]
english please

**Comment by felipepasc** [comment]
Hey, I really like your project!
I really wanted to ask you to add a way to register a SkinProvider
so I can use the skin api!

**Comment by xism4** [comment]
> Hey, I really like your project! I really wanted to ask you to add a way to register a SkinProvider so I can use the skin api!

https://github.com/MrIvanPlays/IvanCord/blob/master/Waterfall-Proxy-Patches/0040-Skins-api.patch

**Comment by MrIvanPlays** [comment]
Skins in IvanCord are only gonna be queried from the Mojang API. If you'd like to change that, create a fork.
